# Numpy Essentials
NumPy is a Python library used for working with arrays. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting funstions that make working with ndarray very easy.

In [1]:
# Computing element-wise operations

import numpy as np

# create two arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# element-wise operation
result = a + b
print(result)

[ 6  8 10 12]


In [2]:
# reverse np array
reverseB  = np.flip(b)

print(a + reverseB)

[9 9 9 9]


In [3]:
# Broadcasting

# create an array and scalar
a = np.array([1, 2, 3, 4])
scalar = 10

# scalar multiplication
print(a * scalar)

[10 20 30 40]


In [8]:
print(scalar * a)

# print(a * scalar) or print(scalar * a)
# Both are same.

[10 20 30 40]


In [9]:
# Generate 5 reandom numbers from a uniform distribution
randomNumbers = np.random.uniform(size=5)
print(randomNumbers)

[0.17744019 0.79480222 0.96345194 0.36282692 0.35052318]


In [11]:
# create two 2-D matrices
A = np.array([ [1, 2], [3, 4] ])
B = np.array([ [5, 6], [7, 8]] )

print(A)

[[1 2]
 [3 4]]


In [12]:
print(B)

[[5 6]
 [7 8]]


In [ ]:
matrix multiplication
print( np.dot(A, B) )